{
 "title": "Activities",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Stress Score per week",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with data as (select date,distance,moving_time,stress from activities order by date) \nselect DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \nsum(stress) as total from data where date >= date_format(ADDDATE(current_date, INTERVAL -(63+WEEKDAY(current_date)) DAY),'%Y-%m-%d') group by weeks order by weeks;"
    }
   ]
  },
  {
   "title": "Fatigue and Fitness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, fitness from fitness;\n\n#with data as (select date, sum(stress) as st from copy group by date order by date)\n#SELECT date,AVG(st) OVER (ORDER BY date RANGE BETWEEN INTERVAL 7 DAY PRECEDING AND CURRENT ROW) AS \"Fatigue\" FROM data;\n\n#with data as (select date,distance,moving_time from copy where type=\"Run\" order by date) \n#select DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \n#sum(distance) as total from data where date >= date_format(ADDDATE(current_date, INTERVAL -(63+WEEKDAY(current_date)) DAY),'%Y-%m-%d') group by weeks order by weeks;\n\n#with data as (select date, sum(stress) as st, ADDDATE(date, INTERVAL -1 DAY) as yesterday from copy group by date order by date)"
    },
    {
     "rawSql": "SELECT date, fatigue from fitness;\n\n#with data as (select date, sum(stress) as st from copy group by date order by date)\n#SELECT date,AVG(st) OVER (ORDER BY date RANGE BETWEEN INTERVAL 42 DAY PRECEDING AND CURRENT ROW) AS \"Fitness\" FROM data;"
    }
   ]
  },
  {
   "title": "Weekly Run DIstance Totals Last 2 Months",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "-- with data as (select date,distance,moving_time from copy where type=\"Run\") select convert(date_format(date,'%x %v'),char) as times, sum(distance) as total from data group by times; --\n\nwith data as (select date,distance,moving_time from activities where type=\"Run\" order by date) \nselect DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \nsum(distance) as total from data where date >= date_format(ADDDATE(current_date, INTERVAL -(63+WEEKDAY(current_date)) DAY),'%Y-%m-%d') group by weeks order by weeks;"
    }
   ]
  },
  {
   "title": "Total Moving Time Multiple Weeks",
   "type": "gauge",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "#with data as (select date,distance,moving_time from activities) select convert(date_format(date,'%x %v'),char) as times, sum(moving_time) as Total from data group by times;\n\nwith data as (select date,distance,moving_time from activities order by date) \nselect DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \nsum(moving_time) as \"Moving Time\" from data where date >= date_format(ADDDATE(current_date, INTERVAL -(35+WEEKDAY(current_date)) DAY),\"%Y-%m-%d\") group by weeks order by weeks;\n\n#number of days back has to be multiple of 7 days (because of number of days in the week)"
    }
   ]
  },
  {
   "title": "Max HR for Week",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with data as (select date,distance,moving_time,avgHR,maxHR from activities where type=\"Run\" order by date) \nselect DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \nmax(maxHR) as total from data where date > date_format(ADDDATE(current_date, INTERVAL -(63+WEEKDAY(current_date)) DAY),\"%Y-%m-%d\") group by weeks order by weeks;"
    }
   ]
  },
  {
   "title": "Moving Time Rolling 7 Day Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT date,SUM(moving_time) OVER (ORDER BY date RANGE BETWEEN INTERVAL 7 DAY PRECEDING AND CURRENT ROW) AS \"All Activities\" FROM activities;"
    },
    {
     "rawSql": "SELECT date,SUM(moving_time) OVER (ORDER BY date RANGE BETWEEN INTERVAL 7 DAY PRECEDING AND CURRENT ROW) AS \"Run\" FROM activities WHERE type=\"Run\";"
    },
    {
     "rawSql": "SELECT date,SUM(moving_time) OVER (ORDER BY date RANGE BETWEEN INTERVAL 7 DAY PRECEDING AND CURRENT ROW) AS \"Gym\" FROM activities WHERE type=\"Gym\";"
    }
   ]
  },
  {
   "title": "Running Distance Rolling 6 Week Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "WITH daily_runs AS (\n  SELECT DATE(date) AS day, SUM(distance) AS daily_distance\n  FROM activities\n  WHERE type = 'Run'\n  GROUP BY DATE(date)\n)\nSELECT \n    f.date,\n    COALESCE(\n      SUM(d.daily_distance) OVER (\n        ORDER BY f.date\n        RANGE BETWEEN INTERVAL 42 DAY PRECEDING AND CURRENT ROW\n      ),\n      0\n    ) AS Running\nFROM fitness f\nLEFT JOIN daily_runs d ON d.day = f.date\nWHERE f.date >= DATE_ADD(CURDATE(), INTERVAL -352 DAY)\nORDER BY f.date;"
    }
   ]
  },
  {
   "title": "Previous Year Running Distance Weekly Total",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    DATE_FORMAT(DATE_SUB(f.date, INTERVAL WEEKDAY(f.date) DAY), '%Y-%m-%d') AS week_start,\n    COALESCE(SUM(a.distance), 0) AS total_distance\nFROM fitness f\nLEFT JOIN activities a\n  ON DATE(a.date) = f.date\n  AND a.type = 'Run'\n  AND a.date >= DATE_ADD(CURDATE(), INTERVAL -352 DAY)\nWHERE f.date >= DATE_ADD(CURDATE(), INTERVAL -352 DAY)\nGROUP BY week_start\nORDER BY week_start;"
    }
   ]
  },
  {
   "title": "Total Moving Time for Week",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "#with data as (select date,distance,moving_time from activities) select convert(date_format(date,'%x %v'),char) as times, sum(moving_time) as Total from data group by times;\n\nwith data as (select date,distance,moving_time from activities order by date) \nselect DATE_FORMAT(ADDDATE(date, INTERVAL 2-WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \nsum(moving_time) as \"Moving Time\" from data where date > date_format(ADDDATE(current_date, INTERVAL -60 DAY),\"%Y-%m-%d\") group by weeks order by weeks;\n\n# TODO: get mondays to display nothing"
    }
   ]
  },
  {
   "title": "Fatigue and Fitness",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT date, fitness from fitness;\n\n#with data as (select date, sum(stress) as st from copy group by date order by date)\n#SELECT date,AVG(st) OVER (ORDER BY date RANGE BETWEEN INTERVAL 7 DAY PRECEDING AND CURRENT ROW) AS \"Fatigue\" FROM data;\n\n#with data as (select date,distance,moving_time from copy where type=\"Run\" order by date) \n#select DATE_FORMAT(ADDDATE(date, INTERVAL -WEEKDAY(date) DAY), '%Y-%m-%d') as weeks, \n#sum(distance) as total from data where date >= date_format(ADDDATE(current_date, INTERVAL -(63+WEEKDAY(current_date)) DAY),'%Y-%m-%d') group by weeks order by weeks;\n\n#with data as (select date, sum(stress) as st, ADDDATE(date, INTERVAL -1 DAY) as yesterday from copy group by date order by date)"
    },
    {
     "rawSql": "SELECT date, fatigue from fitness;\n\n#with data as (select date, sum(stress) as st from copy group by date order by date)\n#SELECT date,AVG(st) OVER (ORDER BY date RANGE BETWEEN INTERVAL 42 DAY PRECEDING AND CURRENT ROW) AS \"Fitness\" FROM data;"
    }
   ]
  },
  {
   "title": "All Time Running Distance Weekly Total",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \n    DATE_FORMAT(DATE_SUB(f.date, INTERVAL WEEKDAY(f.date) DAY), '%Y-%m-%d') AS week_start,\n    COALESCE(SUM(a.distance), 0) AS total_distance\nFROM fitness f\nLEFT JOIN activities a\n  ON DATE(a.date) = f.date\n  AND a.type = 'Run'\n#  AND a.date >= DATE_ADD(CURDATE(), INTERVAL -352 DAY)\n#WHERE f.date >= DATE_ADD(CURDATE(), INTERVAL -352 DAY)\nGROUP BY week_start\nORDER BY week_start;"
    }
   ]
  }
 ]
}